### ISSUE TITLE
似乎缺少了PacketSerializer文件

### ISSUE THREAD

**Issue by huangmeme** [davyxu/CellnetSharp#1]
.gitignore-> Source/PacketSerializer.cs

**Comment by davyxu** [comment]
抱歉,当时由于C#版测试性能不是很好,后期放弃维护
如果实在需要,请参考下面代码的ReadPacket函数进行实现 PacketSerializer.ReadHeader(ps, thisTag);和PacketSerializer.WriteFull(header, payload);两个功能的实现
https://github.com/davyxu/cellorigin/blob/master/client/Assets/Script/Network/ClientSocket.cs

**Comment by huangmeme** [comment]
thx，我看看。
